#name: esewa_flutter_sdk
#description: This is an official Flutter plugin from eSewa to easily integrate eSewa payment into you flutter applications.
#version: 2.0.1+11
#author: eSewa Development
#homepage: https://esewa.com.np/#/home
#documentation: https://developer.esewa.com.np/#/flutter
#
#environment:
#  sdk: '>=2.12.0 <3.0.0'
#  flutter: ">=1.20.0"
#
#dependencies:
#  flutter:
#    sdk: flutter
#
#dev_dependencies:
#  flutter_test:
#    sdk: flutter
#
#flutter:
#  plugin:
#    platforms:
#      android:
#        package: com.f1soft.esewa.esewa_flutter_sdk
#        pluginClass: EsewaFlutterSdkPlugin
#      ios:
#        pluginClass: EsewaFlutterSdkPlugin

name: esewa_flutter_sdk
description: Official Flutter plugin for eSewa payment integration.
#version: 3.0.0+1
version: 2.0.1
author: eSewa Development
homepage: https://esewa.com.np/#/home
documentation: https://developer.esewa.com.np/#/flutter

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  plugin:
    platforms:
      android:
        package: com.f1soft.esewa.esewa_flutter_sdk
        pluginClass: EsewaFlutterSdkPlugin
      ios:
        pluginClass: EsewaFlutterSdkPlugin
