// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-hU5_Zy-O4rG-ZFyLZpzpojO4nkq7T1Y',
    appId: '1:311805614389:web:bea2d43348e331b2d3947c',
    messagingSenderId: '311805614389',
    projectId: 'gighirefirebaseauth',
    authDomain: 'gighirefirebaseauth.firebaseapp.com',
    storageBucket: 'gighirefirebaseauth.firebasestorage.app',
    measurementId: 'G-5VTHKD2XD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByRu3Yi6B66sMaEoY8b_8fVHEy8c9eCyY',
    appId: '1:311805614389:android:260fb5993e239972d3947c',
    messagingSenderId: '311805614389',
    projectId: 'gighirefirebaseauth',
    storageBucket: 'gighirefirebaseauth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDExzO3Ipzsvt9CLhuNv-x6ioEk7XGKLhQ',
    appId: '1:311805614389:ios:6421fbd82da685c5d3947c',
    messagingSenderId: '311805614389',
    projectId: 'gighirefirebaseauth',
    storageBucket: 'gighirefirebaseauth.firebasestorage.app',
    iosBundleId: 'com.example.gighire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDExzO3Ipzsvt9CLhuNv-x6ioEk7XGKLhQ',
    appId: '1:311805614389:ios:6421fbd82da685c5d3947c',
    messagingSenderId: '311805614389',
    projectId: 'gighirefirebaseauth',
    storageBucket: 'gighirefirebaseauth.firebasestorage.app',
    iosBundleId: 'com.example.gighire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-hU5_Zy-O4rG-ZFyLZpzpojO4nkq7T1Y',
    appId: '1:311805614389:web:297f9c86a0384615d3947c',
    messagingSenderId: '311805614389',
    projectId: 'gighirefirebaseauth',
    authDomain: 'gighirefirebaseauth.firebaseapp.com',
    storageBucket: 'gighirefirebaseauth.firebasestorage.app',
    measurementId: 'G-J4Z70EX6DW',
  );
}
